### ISSUE TITLE
The Edit option does nothing

### ISSUE THREAD

**Issue by RubenSibon** [Naheel-Azawy/gnome-shell-extension-desktop-editor#2]
As someone mentioned on this [extension's page in GNOME Shell extensions](https://extensions.gnome.org/extension/1235/desktop-editor/) the "Edit" option in the context menu does nothing; i.e. no editor is opened.

This has probably been the case since gnome-shell 3.18 if the other user is to go by:
"The "Edit" command appears but it does nothing. I use gnome-shell 3.18. Can you fix it?"

**Comment by Naheel-Azawy** [comment]
@RubenSibon Hello! Thanks for your interest in this! Sorry for too late response but I'm getting extremely busy lately... This hasn't been updated for long because I moved from gnome a while ago. For the edit option it simply used to run gedit or whatever editor, it shouldn't be too hard to fix I guess. Maybe someone out there can fix it? Or maybe when I get some free time I will try to install gnome and fix it. I actually kind of miss gnome xD

**Comment by darkretailer** [comment]
@RubenSibon if this is still important for you:

My problem was the gnome-terminal. It does not accept the command without an "-e".
So I did:
`git clone https://github.com/Naheel-Azawy/gnome-shell-extension-desktop-editor.git`
run install.sh in the directory
reload your environment.
Set the following changes:

- Editor: vim
- GUI SU: su
- Terminal: gnome-terminal -e

Of course you can use any terminal-editor (nano, mcedit etc.).
Another way should be to use another terminal.

I hope this also helps someone else.

**Comment by RubenSibon** [comment]
To get back on this. Like Naheel, I also moved away from GNOME (to Elementary OS), but I'm sure that your solutions works. If I every come back I might try it out. For now I will close the issue as it seems to be resolved.
